# Data Cleaning 

## Import Libraries

In [1]:
import os
import pandas as pd
import numpy as np

RAW_DIR = "../data/raw"
CLEAN_DIR = "../data/cleaned"
os.makedirs(CLEAN_DIR, exist_ok=True)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)

## Load Metadata

In [2]:
programs = pd.read_csv(f"{RAW_DIR}/programs.csv")
users = pd.read_csv(f"{RAW_DIR}/users.csv")
applications = pd.read_csv(f"{RAW_DIR}/applications.csv")
pods = pd.read_csv(f"{RAW_DIR}/pods.csv")
project_groups = pd.read_csv(f"{RAW_DIR}/project_groups.csv")
ta_assignments = pd.read_csv(f"{RAW_DIR}/ta_assignments.csv")
daily_engagement = pd.read_csv(f"{RAW_DIR}/daily_engagement.csv")
assessments = pd.read_csv(f"{RAW_DIR}/assessments.csv")
surveys = pd.read_csv(f"{RAW_DIR}/surveys.csv")
dropouts = pd.read_csv(f"{RAW_DIR}/dropouts.csv")
support_requests = pd.read_csv(f"{RAW_DIR}/support_requests.csv")
ta_feedback = pd.read_csv(f"{RAW_DIR}/ta_feedback.csv")
pod_checkins = pd.read_csv(f"{RAW_DIR}/pod_checkins.csv")

## Audit Dataframes

In [3]:
def audit_df(df, name):
    print(f"\n{'='*80}")
    print(f"{name.upper()}")
    print(f"{'='*80}")
    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())
    print("\nDtypes:")
    print(df.dtypes)
    print("\nMissing values:")
    print(df.isnull().sum())
    print("\nDuplicate rows:", df.duplicated().sum())
    print("\nHead:")
    display(df.head())

In [4]:
dfs = {
    "programs": programs,
    "users": users,
    "applications": applications,
    "pods": pods,
    "project_groups": project_groups,
    "ta_assignments": ta_assignments,
    "daily_engagement": daily_engagement,
    "assessments": assessments,
    "surveys": surveys,
    "dropouts": dropouts,
    "support_requests": support_requests,
    "ta_feedback": ta_feedback,
    "pod_checkins": pod_checkins
}

for name, df in dfs.items():
    audit_df(df, name)

================================================================================
PROGRAMS
================================================================================
Shape: (8, 14)

Columns:
['program_id', 'program_name', 'year', 'start_date', 'end_date', 'num_students', 'num_tas', 'region_focus', 'curriculum_hours_per_day', 'project_hours_per_day', 'total_hours_per_day', 'days_per_week', 'delivery_mode', 'num_timeslots']

Dtypes:
program_id                   object
program_name                 object
year                          int64
start_date                   object
end_date                     object
num_students                  int64
num_tas                       int64
region_focus                 object
curriculum_hours_per_day    float64
project_hours_per_day         int64
total_hours_per_day           int64
days_per_week                 int64
delivery_mode                object
num_timeslots                 int64
dtype: object

Missing values:
program_id                  0
program_name                0
year                        0
start_date                  0
end_date                    0
num_students                0
num_tas                     0
region_focus                0
curriculum_hours_per_day    0
project_hours_per_day       0
total_hours_per_day         0
days_per_week               0
delivery_mode               0
num_timeslots               0
dtype: int64

Duplicate rows: 0

Head:

,program_id,program_name,year,start_date,end_date,num_students,num_tas,region_focus,curriculum_hours_per_day,project_hours_per_day,total_hours_per_day,days_per_week,delivery_mode,num_timeslots
0,P001,Computational Neuroscience,2025,2025-06-22,2025-07-24,363,18,global,4.5,3,8,5,virtual,5
1,P002,Deep Learning,2025,2025-06-22,2025-07-24,206,23,global,4.5,3,8,5,virtual,5
2,P003,Computational Tools for Climate Science,2025,2025-06-22,2025-07-24,262,22,global,4.5,3,8,5,virtual,5
3,P004,NeuroAI,2025,2025-06-22,2025-07-24,235,18,global,4.5,3,8,5,virtual,5
4,P005,Computational Neuroscience,2026,2026-06-22,2026-07-24,373,17,global,4.5,3,8,5,virtual,5

================================================================================
USERS
================================================================================
Shape: (1500, 12)

Columns:
['user_id', 'role', 'country', 'timezone', 'gender', 'education_level', 'field_of_study', 'years_experience', 'prior_neuromatch', 'preferred_language', 'interest_area', 'availability_slot']

Dtypes:
user_id               object
role                  object
country               object
timezone              object
gender                object
education_level       object
field_of_study        object
years_experience       int64
prior_neuromatch       int64
preferred_language    object
interest_area         object
availability_slot     object
dtype: object

Missing values:
user_id               0
role                  0
country               0
timezone              0
gender                0
education_level       0
field_of_study        0
years_experience      0
prior_neuromatch      0
preferred_language    0
interest_area         0
availability_slot     0
dtype: int64

Duplicate rows: 0

Head:

,user_id,role,country,timezone,gender,education_level,field_of_study,years_experience,prior_neuromatch,preferred_language,interest_area,availability_slot
0,U00001,student,Germany,UTC+1,Non-binary,PhD,CS,7,0,Spanish,Time Series,Slot 5
1,U00002,student,Canada,UTC-5,Male,Masters,Neuro,2,0,English,CV,Slot 4
2,U00003,student,UK,UTC+0,Female,UG,AI,4,0,French,Neural Coding,Slot 1
3,U00004,student,Canada,UTC-5,Male,Masters,Neuro,5,0,French,Neural Coding,Slot 4
4,U00005,student,USA,UTC-5,Female,UG,Neuro,5,0,French,Climate,Slot 2

================================================================================
APPLICATIONS
================================================================================
Shape: (1285, 13)

Columns:
['application_id', 'user_id', 'program_id', 'application_date', 'motivation_score', 'cv_score', 'technical_score', 'diversity_score', 'preferred_program_track', 'preferred_timeslot', 'selected', 'waitlisted', 'final_status']

Dtypes:
application_id              object
user_id                     object
program_id                  object
application_date            object
motivation_score           float64
cv_score                   float64
technical_score            float64
diversity_score              int64
preferred_program_track     object
preferred_timeslot          object
selected                     int64
waitlisted                   int64
final_status                object
dtype: object

Missing values:
application_id             0
user_id                    0
program_id                 0
application_date           0
motivation_score           0
cv_score                   0
technical_score            0
diversity_score            0
preferred_program_track    0
preferred_timeslot         0
selected                   0
waitlisted                 0
final_status               0
dtype: int64

Duplicate rows: 0

Head:

,application_id,user_id,program_id,application_date,motivation_score,cv_score,technical_score,diversity_score,preferred_program_track,preferred_timeslot,selected,waitlisted,final_status
0,A000001,U00001,P006,2026-03-01,50.797615,29.745819,90.987390,80,Research,Slot 5,0,1,rejected
1,A000002,U00002,P002,2026-03-01,67.661960,60.104138,68.089247,88,Research,Slot 4,1,0,accepted
2,A000003,U00003,P002,2026-03-01,48.215597,52.180251,47.437501,65,Research,Slot 1,0,1,rejected
3,A000004,U00004,P004,2026-03-01,59.988532,42.779320,65.211858,49,Research,Slot 4,0,1,rejected
4,A000005,U00005,P002,2026-03-01,59.696145,41.891489,78.080857,68,Research,Slot 2,0,1,rejected

================================================================================
PODS
================================================================================
Shape: (30, 9)

Columns:
['pod_id', 'program_id', 'year', 'regular_ta_user_id', 'timeslot', 'language', 'interest_cluster', 'num_students', 'region_mix_score']

Dtypes:
pod_id                 object
program_id             object
year                    int64
regular_ta_user_id     object
timeslot               object
language               object
interest_cluster       object
num_students            int64
region_mix_score      float64
dtype: object

Missing values:
pod_id                0
program_id            0
year                  0
regular_ta_user_id    0
timeslot              0
language              0
interest_cluster      0
num_students          0
region_mix_score      0
dtype: int64

Duplicate rows: 0

Head:

,pod_id,program_id,year,regular_ta_user_id,timeslot,language,interest_cluster,num_students,region_mix_score
0,PD0001,P001,2026,U00979,Slot 4,Spanish,Climate,15,0.96
1,PD0002,P001,2026,U00750,Slot 3,Hindi,Climate,15,0.62
2,PD0003,P001,2026,U00456,Slot 4,English,Time Series,11,0.72
3,PD0004,P002,2026,U01248,Slot 2,English,Time Series,15,0.92
4,PD0005,P002,2026,U00801,Slot 4,Hindi,NLP,15,0.91

================================================================================
PROJECT_GROUPS
================================================================================
Shape: (60, 6)

Columns:
['project_group_id', 'pod_id', 'program_id', 'project_ta_user_id', 'group_topic', 'num_students']

Dtypes:
project_group_id      object
pod_id                object
program_id            object
project_ta_user_id    object
group_topic           object
num_students           int64
dtype: object

Missing values:
project_group_id      0
pod_id                0
program_id            0
project_ta_user_id    0
group_topic           0
num_students          0
dtype: int64

Duplicate rows: 0

Head:

,project_group_id,pod_id,program_id,project_ta_user_id,group_topic,num_students
0,G00001,PD0001,P001,U00367,CV,7
1,G00002,PD0001,P001,U00267,Time Series,7
2,G00003,PD0002,P001,U01243,RL,6
3,G00004,PD0002,P001,U00310,NLP,7
4,G00005,PD0003,P001,U00020,RL,5

================================================================================
TA_ASSIGNMENTS
================================================================================
Shape: (90, 5)

Columns:
['user_id', 'program_id', 'pod_id', 'project_group_id', 'ta_role']

Dtypes:
user_id             object
program_id          object
pod_id              object
project_group_id    object
ta_role             object
dtype: object

Missing values:
user_id              0
program_id           0
pod_id               0
project_group_id    30
ta_role              0
dtype: int64

Duplicate rows: 0

Head:

  user_id program_id  pod_id project_group_id     ta_role
0  U00979       P001  PD0001              NaN  regular_ta
1  U00750       P001  PD0002              NaN  regular_ta
2  U00456       P001  PD0003              NaN  regular_ta
3  U01248       P002  PD0004              NaN  regular_ta
4  U00801       P002  PD0005              NaN  regular_ta

================================================================================
DAILY_ENGAGEMENT
================================================================================
Shape: (7440, 11)

Columns:
['user_id', 'program_id', 'day', 'attended_curriculum', 'attended_project', 'curriculum_hours_attended', 'project_hours_attended', 'zoom_minutes', 'assignments_completed', 'forum_messages', 'help_requests']

Dtypes:
user_id                       object
program_id                    object
day                            int64
attended_curriculum            int64
attended_project               int64
curriculum_hours_attended    float64
project_hours_attended       float64
zoom_minutes                   int64
assignments_completed          int64
forum_messages                 int64
help_requests                  int64
dtype: object

Missing values:
user_id                      0
program_id                   0
day                          0
attended_curriculum          0
attended_project             0
curriculum_hours_attended    0
project_hours_attended       0
zoom_minutes                 0
assignments_completed        0
forum_messages               0
help_requests                0
dtype: int64

Duplicate rows: 0

Head:

,user_id,program_id,day,attended_curriculum,attended_project,curriculum_hours_attended,project_hours_attended,zoom_minutes,assignments_completed,forum_messages,help_requests
0,U00002,P002,1,1,1,3.85,1.16,133,1,1,1
1,U00002,P002,2,1,1,2.86,1.74,278,1,8,2
2,U00002,P002,3,1,1,3.97,2.50,162,1,9,0
3,U00002,P002,4,0,0,2.74,2.25,199,0,1,3
4,U00002,P002,5,0,0,2.18,2.66,299,0,4,0

================================================================================
ASSESSMENTS
================================================================================
Shape: (744, 6)

Columns:
['assessment_id', 'user_id', 'program_id', 'type', 'score', 'date']

Dtypes:
assessment_id    object
user_id          object
program_id       object
type             object
score             int64
date             object
dtype: object

Missing values:
assessment_id    0
user_id          0
program_id       0
type             0
score            0
date             0
dtype: int64

Duplicate rows: 0

Head:

  assessment_id user_id program_id  type  score        date
0       AS00001  U00002       P002   pre     48  2026-06-22
1       AS00002  U00002       P002  post     66  2026-07-24
2       AS00003  U00007       P004   pre     47  2026-06-22
3       AS00004  U00007       P004  post     52  2026-07-24
4       AS00005  U00008       P007   pre     66  2026-06-22

================================================================================
SURVEYS
================================================================================
Shape: (372, 10)

Columns:
['survey_id', 'user_id', 'program_id', 'survey_type', 'satisfaction', 'difficulty', 'content_quality', 'ta_support', 'open_feedback', 'response_date']

Dtypes:
survey_id          object
user_id            object
program_id         object
survey_type        object
satisfaction        int64
difficulty          int64
content_quality     int64
ta_support          int64
open_feedback      object
response_date      object
dtype: object

Missing values:
survey_id          0
user_id            0
program_id         0
survey_type        0
satisfaction       0
difficulty         0
content_quality    0
ta_support         0
open_feedback      0
response_date      0
dtype: int64

Duplicate rows: 0

Head:

,survey_id,user_id,program_id,survey_type,satisfaction,difficulty,content_quality,ta_support,open_feedback,response_date
0,S00001,U00002,P002,post,4,4,5,4,Education only sign person office stage both.,2026-07-24
1,S00002,U00007,P004,post,5,2,4,3,City play affect paper.,2026-07-24
2,S00003,U00008,P007,post,5,3,4,3,Point a that pretty project how single she.,2026-07-24
3,S00004,U00014,P006,post,3,2,4,4,Fast building explain.,2026-07-24
4,S00005,U00016,P003,post,3,2,4,4,Others catch of weight animal drop.,2026-07-24

================================================================================
DROPOUTS
================================================================================
Shape: (39, 4)

Columns:
['user_id', 'program_id', 'dropout_day', 'reason']

Dtypes:
user_id        object
program_id     object
dropout_day     int64
reason         object
dtype: object

Missing values:
user_id        0
program_id     0
dropout_day    0
reason         0
dtype: int64

Duplicate rows: 0

Head:

  user_id program_id  dropout_day           reason
0  U00064       P002           20       difficulty
1  U00089       P004           13       difficulty
2  U00115       P006           17   low_engagement
3  U00154       P006            9  time_constraint
4  U00158       P001           19       difficulty

================================================================================
SUPPORT_REQUESTS
================================================================================
Shape: (300, 8)

Columns:
['ticket_id', 'user_id', 'program_id', 'channel', 'issue_type', 'response_time_hours', 'resolved', 'satisfaction']

Dtypes:
ticket_id               object
user_id                 object
program_id              object
channel                 object
issue_type              object
response_time_hours    float64
resolved                 int64
satisfaction             int64
dtype: object

Missing values:
ticket_id              0
user_id                0
program_id             0
channel                0
issue_type             0
response_time_hours    0
resolved               0
satisfaction           0
dtype: int64

Duplicate rows: 0

Head:

,ticket_id,user_id,program_id,channel,issue_type,response_time_hours,resolved,satisfaction
0,T00000,U01218,P005,email,admin,9.22,1,5
1,T00001,U00720,P008,discord,technical,5.68,1,3
2,T00002,U00612,P004,discord,admin,20.15,1,4
3,T00003,U00206,P007,email,technical,14.43,1,4
4,T00004,U01060,P006,email,admin,17.78,1,3

================================================================================
TA_FEEDBACK
================================================================================
Shape: (90, 7)

Columns:
['user_id', 'program_id', 'ta_role', 'avg_student_rating', 'num_sessions_taken', 'response_time_avg', 'engagement_score']

Dtypes:
user_id                object
program_id             object
ta_role                object
avg_student_rating    float64
num_sessions_taken      int64
response_time_avg     float64
engagement_score      float64
dtype: object

Missing values:
user_id               0
program_id            0
ta_role               0
avg_student_rating    0
num_sessions_taken    0
response_time_avg     0
engagement_score      0
dtype: int64

Duplicate rows: 0

Head:

,user_id,program_id,ta_role,avg_student_rating,num_sessions_taken,response_time_avg,engagement_score
0,U00979,P001,regular_ta,4.75,17,8.00,0.81
1,U00750,P001,regular_ta,4.63,8,4.22,0.52
2,U00456,P001,regular_ta,4.60,8,9.51,0.64
3,U01248,P002,regular_ta,4.41,14,4.05,0.55
4,U00801,P002,regular_ta,3.57,17,1.13,0.57

================================================================================
POD_CHECKINS
================================================================================
Shape: (600, 7)

Columns:
['checkin_id', 'pod_id', 'program_id', 'day', 'completed', 'issues_reported', 'mood_score']

Dtypes:
checkin_id         object
pod_id             object
program_id         object
day                 int64
completed           int64
issues_reported     int64
mood_score          int64
dtype: object

Missing values:
checkin_id         0
pod_id             0
program_id         0
day                0
completed          0
issues_reported    0
mood_score         0
dtype: int64

Duplicate rows: 0

Head:

  checkin_id  pod_id program_id  day  completed  issues_reported  mood_score
0     C00001  PD0001       P001    1          1                3           4
1     C00002  PD0001       P001    2          1                2           2
2     C00003  PD0001       P001    3          1                2           3
3     C00004  PD0001       P001    4          1                2           4
4     C00005  PD0001       P001    5          1                2           5

## Cleaning Metadata

In [5]:
programs.head()

,program_id,program_name,year,start_date,end_date,num_students,num_tas,region_focus,curriculum_hours_per_day,project_hours_per_day,total_hours_per_day,days_per_week,delivery_mode,num_timeslots
0,P001,Computational Neuroscience,2025,2025-06-22,2025-07-24,363,18,global,4.5,3,8,5,virtual,5
1,P002,Deep Learning,2025,2025-06-22,2025-07-24,206,23,global,4.5,3,8,5,virtual,5
2,P003,Computational Tools for Climate Science,2025,2025-06-22,2025-07-24,262,22,global,4.5,3,8,5,virtual,5
3,P004,NeuroAI,2025,2025-06-22,2025-07-24,235,18,global,4.5,3,8,5,virtual,5
4,P005,Computational Neuroscience,2026,2026-06-22,2026-07-24,373,17,global,4.5,3,8,5,virtual,5

In [6]:
programs = programs.drop_duplicates()

date_cols = ["start_date", "end_date"]
for col in date_cols:
    programs[col] = pd.to_datetime(programs[col], errors="coerce")

programs["year"] = programs["year"].astype("Int64")
programs["num_students"] = programs["num_students"].astype("Int64")
programs["num_tas"] = programs["num_tas"].astype("Int64")

programs["delivery_mode"] = programs["delivery_mode"].str.strip().str.lower()
programs["region_focus"] = programs["region_focus"].str.strip().str.lower()

programs.head()

,program_id,program_name,year,start_date,end_date,num_students,num_tas,region_focus,curriculum_hours_per_day,project_hours_per_day,total_hours_per_day,days_per_week,delivery_mode,num_timeslots
0,P001,Computational Neuroscience,2025,2025-06-22,2025-07-24,363,18,global,4.5,3,8,5,virtual,5
1,P002,Deep Learning,2025,2025-06-22,2025-07-24,206,23,global,4.5,3,8,5,virtual,5
2,P003,Computational Tools for Climate Science,2025,2025-06-22,2025-07-24,262,22,global,4.5,3,8,5,virtual,5
3,P004,NeuroAI,2025,2025-06-22,2025-07-24,235,18,global,4.5,3,8,5,virtual,5
4,P005,Computational Neuroscience,2026,2026-06-22,2026-07-24,373,17,global,4.5,3,8,5,virtual,5

In [7]:
users = users.drop_duplicates()

users["role"] = users["role"].str.strip().str.lower()
users["country"] = users["country"].str.strip()
users["timezone"] = users["timezone"].str.strip()
users["gender"] = users["gender"].fillna("Prefer not to say").str.strip()
users["education_level"] = users["education_level"].str.strip()
users["field_of_study"] = users["field_of_study"].str.strip()
users["preferred_language"] = users["preferred_language"].str.strip()
users["interest_area"] = users["interest_area"].str.strip()
users["availability_slot"] = users["availability_slot"].str.strip()

users["years_experience"] = pd.to_numeric(users["years_experience"], errors="coerce").fillna(0).astype(int)
users["prior_neuromatch"] = pd.to_numeric(users["prior_neuromatch"], errors="coerce").fillna(0).astype(int)

# Valid role check
valid_roles = ["student", "ta", "instructor"]
users = users[users["role"].isin(valid_roles)]

users.head()

,user_id,role,country,timezone,gender,education_level,field_of_study,years_experience,prior_neuromatch,preferred_language,interest_area,availability_slot
0,U00001,student,Germany,UTC+1,Non-binary,PhD,CS,7,0,Spanish,Time Series,Slot 5
1,U00002,student,Canada,UTC-5,Male,Masters,Neuro,2,0,English,CV,Slot 4
2,U00003,student,UK,UTC+0,Female,UG,AI,4,0,French,Neural Coding,Slot 1
3,U00004,student,Canada,UTC-5,Male,Masters,Neuro,5,0,French,Neural Coding,Slot 4
4,U00005,student,USA,UTC-5,Female,UG,Neuro,5,0,French,Climate,Slot 2

In [8]:
applications = applications.drop_duplicates()

applications["application_date"] = pd.to_datetime(applications["application_date"], errors="coerce")

score_cols = ["motivation_score", "cv_score", "technical_score", "diversity_score"]
for col in score_cols:
    applications[col] = pd.to_numeric(applications[col], errors="coerce").clip(0, 100)

binary_cols = ["selected", "waitlisted"]
for col in binary_cols:
    applications[col] = pd.to_numeric(applications[col], errors="coerce").fillna(0).astype(int)

applications["final_status"] = applications["final_status"].str.strip().str.lower()
applications["preferred_program_track"] = applications["preferred_program_track"].astype(str).str.strip()
applications["preferred_timeslot"] = applications["preferred_timeslot"].astype(str).str.strip()

applications.head()

,application_id,user_id,program_id,application_date,motivation_score,cv_score,technical_score,diversity_score,preferred_program_track,preferred_timeslot,selected,waitlisted,final_status
0,A000001,U00001,P006,2026-03-01,50.797615,29.745819,90.987390,80,Research,Slot 5,0,1,rejected
1,A000002,U00002,P002,2026-03-01,67.661960,60.104138,68.089247,88,Research,Slot 4,1,0,accepted
2,A000003,U00003,P002,2026-03-01,48.215597,52.180251,47.437501,65,Research,Slot 1,0,1,rejected
3,A000004,U00004,P004,2026-03-01,59.988532,42.779320,65.211858,49,Research,Slot 4,0,1,rejected
4,A000005,U00005,P002,2026-03-01,59.696145,41.891489,78.080857,68,Research,Slot 2,0,1,rejected

In [9]:
pods = pods.drop_duplicates()

pods["year"] = pd.to_numeric(pods["year"], errors="coerce").astype("Int64")
pods["num_students"] = pd.to_numeric(pods["num_students"], errors="coerce").astype("Int64")
pods["region_mix_score"] = pd.to_numeric(pods["region_mix_score"], errors="coerce").clip(0, 1)

pods["timeslot"] = pods["timeslot"].astype(str).str.strip()
pods["language"] = pods["language"].astype(str).str.strip()
pods["interest_cluster"] = pods["interest_cluster"].astype(str).str.strip()

pods.head()

,pod_id,program_id,year,regular_ta_user_id,timeslot,language,interest_cluster,num_students,region_mix_score
0,PD0001,P001,2026,U00979,Slot 4,Spanish,Climate,15,0.96
1,PD0002,P001,2026,U00750,Slot 3,Hindi,Climate,15,0.62
2,PD0003,P001,2026,U00456,Slot 4,English,Time Series,11,0.72
3,PD0004,P002,2026,U01248,Slot 2,English,Time Series,15,0.92
4,PD0005,P002,2026,U00801,Slot 4,Hindi,NLP,15,0.91

In [10]:
project_groups = project_groups.drop_duplicates()

project_groups["num_students"] = pd.to_numeric(project_groups["num_students"], errors="coerce").astype("Int64")
project_groups["group_topic"] = project_groups["group_topic"].astype(str).str.strip()

project_groups.head()

,project_group_id,pod_id,program_id,project_ta_user_id,group_topic,num_students
0,G00001,PD0001,P001,U00367,CV,7
1,G00002,PD0001,P001,U00267,Time Series,7
2,G00003,PD0002,P001,U01243,RL,6
3,G00004,PD0002,P001,U00310,NLP,7
4,G00005,PD0003,P001,U00020,RL,5

In [12]:
ta_assignments = ta_assignments.drop_duplicates()

ta_assignments["ta_role"] = ta_assignments["ta_role"].astype(str).str.strip().str.lower()

valid_ta_roles = ["regular_ta", "project_ta"]
ta_assignments = ta_assignments[ta_assignments["ta_role"].isin(valid_ta_roles)]

ta_assignments.head()

  user_id program_id  pod_id project_group_id     ta_role
0  U00979       P001  PD0001              NaN  regular_ta
1  U00750       P001  PD0002              NaN  regular_ta
2  U00456       P001  PD0003              NaN  regular_ta
3  U01248       P002  PD0004              NaN  regular_ta
4  U00801       P002  PD0005              NaN  regular_ta

In [13]:
daily_engagement = daily_engagement.drop_duplicates()

daily_engagement["day"] = pd.to_numeric(daily_engagement["day"], errors="coerce").astype("Int64")

binary_cols = ["attended_curriculum", "attended_project", "assignments_completed"]
for col in binary_cols:
    daily_engagement[col] = pd.to_numeric(daily_engagement[col], errors="coerce").fillna(0).astype(int)

num_cols = ["curriculum_hours_attended", "project_hours_attended", "zoom_minutes", "forum_messages", "help_requests"]
for col in num_cols:
    daily_engagement[col] = pd.to_numeric(daily_engagement[col], errors="coerce").fillna(0)

# clip realistic bounds
daily_engagement["curriculum_hours_attended"] = daily_engagement["curriculum_hours_attended"].clip(0, 4.5)
daily_engagement["project_hours_attended"] = daily_engagement["project_hours_attended"].clip(0, 3.0)
daily_engagement["zoom_minutes"] = daily_engagement["zoom_minutes"].clip(0, 480)

daily_engagement.head()

,user_id,program_id,day,attended_curriculum,attended_project,curriculum_hours_attended,project_hours_attended,zoom_minutes,assignments_completed,forum_messages,help_requests
0,U00002,P002,1,1,1,3.85,1.16,133,1,1,1
1,U00002,P002,2,1,1,2.86,1.74,278,1,8,2
2,U00002,P002,3,1,1,3.97,2.50,162,1,9,0
3,U00002,P002,4,0,0,2.74,2.25,199,0,1,3
4,U00002,P002,5,0,0,2.18,2.66,299,0,4,0

In [14]:
assessments = assessments.drop_duplicates()

assessments["score"] = pd.to_numeric(assessments["score"], errors="coerce").clip(0, 100)
assessments["date"] = pd.to_datetime(assessments["date"], errors="coerce")
assessments["type"] = assessments["type"].astype(str).str.strip().str.lower()

valid_assessment_types = ["pre", "mid", "post"]
assessments = assessments[assessments["type"].isin(valid_assessment_types)]

assessments.head()

  assessment_id user_id program_id  type  score       date
0       AS00001  U00002       P002   pre     48 2026-06-22
1       AS00002  U00002       P002  post     66 2026-07-24
2       AS00003  U00007       P004   pre     47 2026-06-22
3       AS00004  U00007       P004  post     52 2026-07-24
4       AS00005  U00008       P007   pre     66 2026-06-22

In [15]:
surveys = surveys.drop_duplicates()

surveys["survey_type"] = surveys["survey_type"].astype(str).str.strip().str.lower()
surveys["response_date"] = pd.to_datetime(surveys["response_date"], errors="coerce")
surveys["open_feedback"] = surveys["open_feedback"].fillna("").astype(str)

rating_cols = ["satisfaction", "difficulty", "content_quality", "ta_support"]
for col in rating_cols:
    surveys[col] = pd.to_numeric(surveys[col], errors="coerce").clip(1, 5)

valid_survey_types = ["pre", "mid", "post"]
surveys = surveys[surveys["survey_type"].isin(valid_survey_types)]

surveys.head()

,survey_id,user_id,program_id,survey_type,satisfaction,difficulty,content_quality,ta_support,open_feedback,response_date
0,S00001,U00002,P002,post,4,4,5,4,Education only sign person office stage both.,2026-07-24
1,S00002,U00007,P004,post,5,2,4,3,City play affect paper.,2026-07-24
2,S00003,U00008,P007,post,5,3,4,3,Point a that pretty project how single she.,2026-07-24
3,S00004,U00014,P006,post,3,2,4,4,Fast building explain.,2026-07-24
4,S00005,U00016,P003,post,3,2,4,4,Others catch of weight animal drop.,2026-07-24

In [16]:
dropouts = dropouts.drop_duplicates()

dropouts["dropout_day"] = pd.to_numeric(dropouts["dropout_day"], errors="coerce").astype("Int64")
dropouts["reason"] = dropouts["reason"].astype(str).str.strip().str.lower()

valid_dropout_reasons = ["low_engagement", "time_constraint", "difficulty"]
dropouts = dropouts[dropouts["reason"].isin(valid_dropout_reasons)]

dropouts.head()

  user_id program_id  dropout_day           reason
0  U00064       P002           20       difficulty
1  U00089       P004           13       difficulty
2  U00115       P006           17   low_engagement
3  U00154       P006            9  time_constraint
4  U00158       P001           19       difficulty

In [17]:
support_requests = support_requests.drop_duplicates()

support_requests["channel"] = support_requests["channel"].astype(str).str.strip().str.lower()
support_requests["issue_type"] = support_requests["issue_type"].astype(str).str.strip().str.lower()

support_requests["response_time_hours"] = pd.to_numeric(
    support_requests["response_time_hours"], errors="coerce"
).fillna(0).clip(0, 168)

support_requests["resolved"] = pd.to_numeric(
    support_requests["resolved"], errors="coerce"
).fillna(0).astype(int)

support_requests["satisfaction"] = pd.to_numeric(
    support_requests["satisfaction"], errors="coerce"
).clip(1, 5)

support_requests.head()

,ticket_id,user_id,program_id,channel,issue_type,response_time_hours,resolved,satisfaction
0,T00000,U01218,P005,email,admin,9.22,1,5
1,T00001,U00720,P008,discord,technical,5.68,1,3
2,T00002,U00612,P004,discord,admin,20.15,1,4
3,T00003,U00206,P007,email,technical,14.43,1,4
4,T00004,U01060,P006,email,admin,17.78,1,3

In [18]:
ta_feedback = ta_feedback.drop_duplicates()

ta_feedback["ta_role"] = ta_feedback["ta_role"].astype(str).str.strip().str.lower()

ta_feedback["avg_student_rating"] = pd.to_numeric(
    ta_feedback["avg_student_rating"], errors="coerce"
).clip(1, 5)

ta_feedback["num_sessions_taken"] = pd.to_numeric(
    ta_feedback["num_sessions_taken"], errors="coerce"
).fillna(0).astype(int)

ta_feedback["response_time_avg"] = pd.to_numeric(
    ta_feedback["response_time_avg"], errors="coerce"
).fillna(0)

ta_feedback["engagement_score"] = pd.to_numeric(
    ta_feedback["engagement_score"], errors="coerce"
).clip(0, 1)

ta_feedback.head()

,user_id,program_id,ta_role,avg_student_rating,num_sessions_taken,response_time_avg,engagement_score
0,U00979,P001,regular_ta,4.75,17,8.00,0.81
1,U00750,P001,regular_ta,4.63,8,4.22,0.52
2,U00456,P001,regular_ta,4.60,8,9.51,0.64
3,U01248,P002,regular_ta,4.41,14,4.05,0.55
4,U00801,P002,regular_ta,3.57,17,1.13,0.57

In [19]:
pod_checkins = pod_checkins.drop_duplicates()

pod_checkins["day"] = pd.to_numeric(pod_checkins["day"], errors="coerce").astype("Int64")
pod_checkins["completed"] = pd.to_numeric(pod_checkins["completed"], errors="coerce").fillna(0).astype(int)
pod_checkins["issues_reported"] = pd.to_numeric(pod_checkins["issues_reported"], errors="coerce").fillna(0).astype(int)
pod_checkins["mood_score"] = pd.to_numeric(pod_checkins["mood_score"], errors="coerce").clip(1, 5)

pod_checkins.head()

  checkin_id  pod_id program_id  day  completed  issues_reported  mood_score
0     C00001  PD0001       P001    1          1                3           4
1     C00002  PD0001       P001    2          1                2           2
2     C00003  PD0001       P001    3          1                2           3
3     C00004  PD0001       P001    4          1                2           4
4     C00005  PD0001       P001    5          1                2           5

In [20]:
print("Programs unique IDs:", programs["program_id"].is_unique)
print("Users unique IDs:", users["user_id"].is_unique)
print("Applications unique IDs:", applications["application_id"].is_unique)
print("Pods unique IDs:", pods["pod_id"].is_unique)
print("Project groups unique IDs:", project_groups["project_group_id"].is_unique)
print("Assessments unique IDs:", assessments["assessment_id"].is_unique)
print("Surveys unique IDs:", surveys["survey_id"].is_unique)
print("Support requests unique IDs:", support_requests["ticket_id"].is_unique)
print("Pod checkins unique IDs:", pod_checkins["checkin_id"].is_unique)

Programs unique IDs: True
Users unique IDs: True
Applications unique IDs: True
Pods unique IDs: True
Project groups unique IDs: True
Assessments unique IDs: True
Surveys unique IDs: True
Support requests unique IDs: True
Pod checkins unique IDs: True

In [21]:
print("applications.user_id in users:", applications["user_id"].isin(users["user_id"]).all())
print("applications.program_id in programs:", applications["program_id"].isin(programs["program_id"]).all())

print("pods.program_id in programs:", pods["program_id"].isin(programs["program_id"]).all())
print("pods.regular_ta_user_id in users:", pods["regular_ta_user_id"].isin(users["user_id"]).all())

print("project_groups.pod_id in pods:", project_groups["pod_id"].isin(pods["pod_id"]).all())
print("project_groups.program_id in programs:", project_groups["program_id"].isin(programs["program_id"]).all())

print("daily_engagement.user_id in users:", daily_engagement["user_id"].isin(users["user_id"]).all())
print("daily_engagement.program_id in programs:", daily_engagement["program_id"].isin(programs["program_id"]).all())

applications.user_id in users: True
applications.program_id in programs: True
pods.program_id in programs: True
pods.regular_ta_user_id in users: True
project_groups.pod_id in pods: True
project_groups.program_id in programs: True
daily_engagement.user_id in users: True
daily_engagement.program_id in programs: True

In [22]:
programs.to_csv(f"{CLEAN_DIR}/programs_clean.csv", index=False)
users.to_csv(f"{CLEAN_DIR}/users_clean.csv", index=False)
applications.to_csv(f"{CLEAN_DIR}/applications_clean.csv", index=False)
pods.to_csv(f"{CLEAN_DIR}/pods_clean.csv", index=False)
project_groups.to_csv(f"{CLEAN_DIR}/project_groups_clean.csv", index=False)
ta_assignments.to_csv(f"{CLEAN_DIR}/ta_assignments_clean.csv", index=False)
daily_engagement.to_csv(f"{CLEAN_DIR}/daily_engagement_clean.csv", index=False)
assessments.to_csv(f"{CLEAN_DIR}/assessments_clean.csv", index=False)
surveys.to_csv(f"{CLEAN_DIR}/surveys_clean.csv", index=False)
dropouts.to_csv(f"{CLEAN_DIR}/dropouts_clean.csv", index=False)
support_requests.to_csv(f"{CLEAN_DIR}/support_requests_clean.csv", index=False)
ta_feedback.to_csv(f"{CLEAN_DIR}/ta_feedback_clean.csv", index=False)
pod_checkins.to_csv(f"{CLEAN_DIR}/pod_checkins_clean.csv", index=False)

print("✅ All cleaned CSVs saved to data/cleaned/")

✅ All cleaned CSVs saved to data/cleaned/